### ISSUE TITLE
ibmcloud tg gateways

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/transit-gateway#1]
There is no tg flag with ibmcloud command. Please update this page:
https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-ha-dr

**Comment by austinmama** [comment]
There is a flag for transit gateway.  You must first install the CLI plug-in.

 
ibmcloud plugin install tg
Looking up 'tg' from repository 'IBM Cloud'...
Plug-in 'tg-cli/tg 0.3.2' found in repository 'IBM Cloud'
