### ISSUE TITLE
Bug: Step 2 directions for CLI

### ISSUE THREAD

**Issue by abacchus-ibm** [ibm-cloud-docs/transit-gateway#10]
In step 2, please change the command from `echo $iam_token` to `echo $IAM_TOKEN`. https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-set-up-environment#get-iam-token

I use the Mac OS Terminal command line utility. In my utility, variables are case-sensitive. The first step in Step 2 sets IAM_TOKEN. The corresponding echo command should be uppercase. The command was successful when I changed the echo statement to uppercase for the variable only > `echo $IAM_TOKEN`.

**Comment by austinmama** [comment]
Updated.  Thank you for your feedback.
