### ISSUE TITLE
Misleading & incorrect information

### ISSUE THREAD

**Issue by tooloudcajun** [ibm-cloud-docs/transit-gateway#11]
The second table under TGW locations https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-tg-locations Labeled "Data Centers" is very misleading to clients.  It reads as if these data centers have TGWs, rather than they have access to TGWs in other Data Centers.  IE MON01 does not have TGW technology, however, can be connect to TGWs in TOR MZR.  It would be helpful if the wording above the table was more clear and an added column to indicate which DC / MZR the TGW would be accessed from.

Also, Madrid | MAD02, MAD04, MAD05 is listed in the Data Center table AND in the MZR Table.  I believe it should only be listed in the MZR table.

**Comment by austinmama** [comment]
Removed Madrid from data center table.  Revised heading and introductory text.  Thank you for your feedback.
