### ISSUE TITLE
Correction in docs required

### ISSUE THREAD

**Issue by Itsmemukesh** [ibm-cloud-docs/transit-gateway#12]
**Where**: https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-ordering-transit-gateway&interface=ui

**Current doc** :
1. Currently, the Power Edge Router (PER) solution is available only in DAL10.
2. NOTE: If you select Power Virtual Server, a Power Virtual Server workspace must be created in a data center after the Power Edge Router has been deployed. For more information, see [Getting started with the Power Edge Router](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-per).

Changes required:

1. Remove the line _Currently, the Power Edge Router (PER) solution is available only in DAL10._ because it is supported in multiple data centers that are listed in the PER page.
2. If you select Power Virtual Server, a Power Virtual Server workspace must be created in a PER-enabled data center.  To see the list of PER-enabled data centers, see [Getting started with the Power Edge Router](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-per).

@austinmama

**Comment by austinmama** [comment]
Updated 6 files

https://github.com/ibm-cloud-docs/transit-gateway/commit/71c74ed31fb618cb47f89eb9fa122a9cbc9014c8
