### ISSUE TITLE
Please add also a chapter for Bare Metal machines in Classics and Transit Gateway

### ISSUE THREAD

**Issue by rmey** [ibm-cloud-docs/transit-gateway#13]
I think the following is also true for bare metal machines:
https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-routing-classic-vsi
_If you are attempting to access an IBM Cloud classic infrastructure virtual server instance that has both a private network interface (eth0) and a public network interface (eth1), then the issue could be the traffic being routed to the public network interface versus the private. The routing tables for these interfaces point the default gateway to the public interface (eth1). Transit gateways are connected only to the private networks. You might have to add entries to route the subnets from other VPCs through the private interface._

**Comment by austinmama** [comment]
Updated topic.  Thank you for your feedback. https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-routing-classic-vsi
