### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/transit-gateway#14]
The link to IBM Cloud cost estimator (https://cloud.ibm.com/cloud/cloud-calculator?mhsrc=ibmsearch_a&mhq=cost%20estimator) at this link gives 404 error: https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-helpful-tips#pricing-considerations

**Comment by austinmama** [comment]
Fixed.  Thank you for your feedback.
