### ISSUE TITLE
transit-gateway link not working

### ISSUE THREAD

**Issue by ramachittala** [ibm-cloud-docs/transit-gateway#3]
We have already trasist gateway available. From where if we click on the `docs` it will be redirecting to https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-edit-gateway
But this page reporting an error. 
![image](https://user-images.githubusercontent.com/25538647/122757048-ca9a7b00-d2b4-11eb-95e7-2994f5994ba7.png)

**Comment by austinmama** [comment]
@jbmitch  Completed?

**Comment by jbmitch** [comment]
Fixed
