### ISSUE TITLE
Could you update the information about the limitation?

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/transit-gateway#6]
Hello,
I think that the “1 IBM Cloud classic infrastructure connection” limit on the “Number of connections per transit gateway” is not valid now.
https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-helpful-tips#service-limits

We are now able to connect from a Transit Gateway to a Classic in a different account. Use case 7 below shows two Classic connections from one Transit Gateway.
https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-about#use-case-7

Could you check and update the information about the limitation?

Thank you,

**Comment by jbmitch** [comment]
fixed.
