### ISSUE TITLE
Adding and deleting prefix filters documentation

### ISSUE THREAD

**Issue by jmsmiddleton** [ibm-cloud-docs/transit-gateway#7]
In regards to this statement -

Only a network account owner can filter prefixes.

- It would be helpful to know how to confirm your account is a network account owner

**Comment by austinmama** [comment]
@jmsmiddleton 

Thank you for your feedback.

Updated from:

* Only a network account owner can filter prefixes.

To:

* Only users in the account that contains the network can filter prefixes of that network.

@jbmitch
