### ISSUE TITLE
Confusion over needing a 2nd connection

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/transit-gateway#8]
ACS-VPC support got case CS3280283 in which customer created a cross-account transit gateway, and added a classic infrastructure connection for the other account (the one they didn't create the TGW connection for).  But since this is the only article they reviewed, they were unaware that they needed to create a second connection, to add classic infrastructure for the same account the transit gateway is in.  They asked if the documentation could be updated to reflect this fact.  Thanks!

**Comment by austinmama** [comment]
@john-d-burke  Added a new statement here: https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-helpful-tips

A transit gateway requires at least two connections before network traffic can flow over the transit gateway. Transit gateways that have less than two connections for 45 days or more are subject to be reclaimed (suspended, then deleted after 30 days).
