### ISSUE TITLE
Broken Link in page

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/transit-gateway#9]
"See [Creating an Unbound Generic Routing Encapsulation tunnel connection](https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-unbound-GRE-connection) for more information."

The link in the above text is broken.  The following link works:

https://cloud.ibm.com/docs/transit-gateway?topic=transit-gateway-unbound-gre-connection&interface=ui

**Comment by austinmama** [comment]
Hi John.  I updated the broken links.  There were a few where a writer used uppercase in the URL.  Thank you for opening an issue.
